Repository rajitha-mahesh/madproject, pull requests merged in 2022-05, with the labels that each got.

#2 updated sign in and sign up
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/madprojectuserinterface/Login.java
  app/src/main/java/com/example/madprojectuserinterface/SignUp.java
  app/src/main/res/drawable/start_page1.png
  app/src/main/res/drawable/start_page2.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/activity_user_update.xml
  build.gradle
Labels: documentation

#4 commit update
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/madprojectuserinterface/ChangePassword.java
  app/src/main/java/com/example/madprojectuserinterface/ConfirmPassword.java
  app/src/main/java/com/example/madprojectuserinterface/Favourites.java
  app/src/main/java/com/example/madprojectuserinterface/FogrtPassword.java
  app/src/main/java/com/example/madprojectuserinterface/InModule.java
  app/src/main/java/com/example/madprojectuserinterface/Module.java
  app/src/main/java/com/example/madprojectuserinterface/Subject.java
  app/src/main/res/drawable/ad_image.jpg
  app/src/main/res/drawable/module_page_btn.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_confirm_password.xml
  app/src/main/res/layout/activity_favourites.xml
  app/src/main/res/layout/activity_fogrt_password.xml
  app/src/main/res/layout/activity_in_module.xml
  app/src/main/res/layout/activity_module.xml
  app/src/main/res/layout/activity_subject.xml
Labels: enhancement

#5 Added user model and firebasestore
  app/.gitignore
  app/build.gradle
  app/src/main/java/com/example/madprojectuserinterface/SignUp.java
  app/src/main/java/com/example/madprojectuserinterface/models/User.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_home.xml
  app/src/main/res/layout/activity_sign_up.xml
Labels: documentation, enhancement

#6 Dev namila
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/activity_user_profile.xml
Labels: enhancement

#7 commit update
  app/src/main/res/layout/activity_fogrt_password.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/activity_user_update.xml
Labels: enhancement

#8 Dev namila
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_side_menu_24.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_home.xml
  app/src/main/res/layout/activity_module.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/activity_user_update.xml
Labels: enhancement

#10 commit update
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/madprojectuserinterface/TestModule.java
  app/src/main/res/drawable/ic_baseline_menu_24.xml
  app/src/main/res/layout/activity_test_module.xml
Labels: enhancement

#11 Dev namila
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/madprojectuserinterface/TestModule1.java
  app/src/main/java/com/example/madprojectuserinterface/TestModule2.java
  app/src/main/java/com/example/madprojectuserinterface/TestModule3.java
  app/src/main/res/layout/activity_test_module1.xml
  app/src/main/res/layout/activity_test_module2.xml
  app/src/main/res/layout/activity_test_module3.xml
Labels: enhancement

#15 popup activity update
  app/src/main/java/com/example/madprojectuserinterface/TestModule1.java
Labels: enhancement

#17 commit update
  app/src/main/res/drawable/ic_baseline_favorite_border_24.xml
  app/src/main/res/drawable/ic_baseline_favorite_red.xml
  app/src/main/res/layout/activity_biology_past_papers.xml
  app/src/main/res/layout/activity_com_math_past_papers.xml
  app/src/main/res/layout/activity_ebooks.xml
  app/src/main/res/layout/activity_favourites.xml
  app/src/main/res/layout/activity_in_module.xml
  app/src/main/res/layout/activity_past_papers.xml
  app/src/main/res/layout/activity_physics_past_papers.xml
Labels: enhancement

#18 commit update
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/madprojectuserinterface/QuestionLibrary.java
  app/src/main/java/com/example/madprojectuserinterface/QuizActivity.java
  app/src/main/res/layout/activity_in_module.xml
  app/src/main/res/layout/activity_question_library.xml
  app/src/main/res/layout/activity_quiz.xml
Labels: enhancement

#21 commit update
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/madprojectuserinterface/Commerce.java
  app/src/main/java/com/example/madprojectuserinterface/InModule.java
  app/src/main/java/com/example/madprojectuserinterface/QuizActivity.java
  app/src/main/java/com/example/madprojectuserinterface/VideoPlayer.java
  app/src/main/res/layout/activity_in_module.xml
  app/src/main/res/layout/activity_quiz.xml
  app/src/main/res/layout/activity_video_player.xml
  app/src/main/res/raw/pendiulum_motion.mp4
Labels: enhancement
